# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-02 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_adminbranch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='number',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
